version: "3.8"

services:

  backend:
    build: ./Backend
    container_name: backend
    network_mode: host
    restart: always
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      WEATHER_API_KEY: "4a76f0f3857b2de460ade8f2f81810c0"
    volumes:
      - ./Backend/vectorstore:/app/vectorstore
      - ./datasets:/app/datasets

  frontend:
    build: ./Front-end
    container_name: frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
